authors = ["kescobo <kevbonham@gmail.com"]
desc = "Functions for working with microbial community data"
keywords = ["microbiology", "microbiome", "biology"]
license = "MIT"
name = "Microbiome"
version = "0.4.0"
uuid = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"

[compat]
julia = "0.7, 1.0"
SpatialEcology = "^0.4"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
