name = "Microbiome"
uuid = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"
keywords = ["microbiology", "microbiome", "biology"]
license = "MIT"
desc = "Functions for working with microbial community data"
authors = ["kescobo <kevbonham@gmail.com>"]
version = "0.7.0-pre"

[deps]
EcoBase = "a58aae7d-b440-5a11-b283-399458f99aac"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
EcoBase = "0.1"
MultivariateStats = "0.7, 0.8"
StatsBase = "0.32, 0.33"
julia = "1.1"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
coverage = ["Coverage"]
test = ["Test", "Random"]
